# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pagelime_rails}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Emil Anticevic"]
  s.date = %q{2012-01-10}
  s.description = %q{}
  s.email = %q{eanticev@gmail.com}
  s.files = [
    "Gemfile",
    "Heroku.md",
    "MIT-LICENSE",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "config/routes.rb",
    "init.rb",
    "install.rb",
    "lib/app/controllers/pagelime_receiver_controller.rb",
    "lib/app/helpers/pagelime_helper.rb",
    "lib/engine.rb",
    "lib/pagelime_rails.rb",
    "lib/routing_extensions.rb",
    "lib/tasks/pagelime.rake",
    "pagelime_rails.gemspec",
    "rails/init.rb",
    "test/pagelime_test.rb",
    "test/test_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/eanticev/pagelime_rails}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Pagelime Rails Plugin}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

